/*
  # V1 — BCI export verification log

  Tracks every generated .bci file: which fields were populated, which
  required fields were missing (the "blocking" gaps), which optional ones
  were missing, and the Best Case import test result.

  The Best Case BCI XML itself is generated by generateBCI(d) in
  src/bankruptcy-information-and-document-questionnaire(1).jsx (~L2075).
  This log is the verification surface — populates docs/BCI_FIELD_GAPS.md
  during the V1 pilot.

  Depends on:
    - clients      (from 20260527010000_create_clients_table.sql)
    - firms        (from 20260527020000_firms_and_user_profiles.sql)
    - user_profiles (from 20260527020000_firms_and_user_profiles.sql)
    - auth.users
*/

CREATE TABLE IF NOT EXISTS bci_verification_logs (
  id                         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id                  uuid REFERENCES clients(id) ON DELETE CASCADE,
  firm_id                    uuid REFERENCES firms(id),
  generated_at               timestamptz NOT NULL DEFAULT now(),
  generated_by               uuid REFERENCES auth.users(id),
  populated_fields_count     integer,
  missing_required_fields    jsonb NOT NULL DEFAULT '[]'::jsonb,
  missing_optional_fields    jsonb NOT NULL DEFAULT '[]'::jsonb,
  bci_storage_path           text,
  bci_file_hash              text,
  file_size_bytes            integer,
  best_case_import_tested    boolean NOT NULL DEFAULT false,
  best_case_import_result    text,
  notes                      text
);

CREATE INDEX IF NOT EXISTS idx_bci_logs_client
  ON bci_verification_logs(client_id, generated_at DESC);

ALTER TABLE bci_verification_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY bci_verification_logs_super_admin_all ON bci_verification_logs
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.user_id = auth.uid()
        AND user_profiles.role = 'super_admin_bankruptcy_ai'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.user_id = auth.uid()
        AND user_profiles.role = 'super_admin_bankruptcy_ai'
    )
  );

CREATE POLICY bci_verification_logs_firm_all ON bci_verification_logs
  FOR ALL
  USING (
    firm_id = (SELECT firm_id FROM user_profiles WHERE user_profiles.user_id = auth.uid())
  )
  WITH CHECK (
    firm_id = (SELECT firm_id FROM user_profiles WHERE user_profiles.user_id = auth.uid())
  );
