/*
  # Add Additional Pleading Templates

  Adds 6 new template pleadings to the legal document portal:
  1. Motion to Confirm Chapter 13 Plan
  2. Notice of Conversion (Ch. 13 to Ch. 7)
  3. Motion to Convert from Chapter 7 to Chapter 13
  4. Motion to Dismiss Case (Voluntary)
  5. Motion to Avoid Judicial Lien
  6. Motion to Value Collateral (Strip Lien / Cram Down)

  Also adds corresponding ECF rules for motion-to-value and lien-avoidance filing types.
*/

-- ── New ECF rule filing types for new motions ────────────────────────────────
INSERT INTO ecf_rules (filing_type, rule_name, task_title, deadline_days, priority, auto_calendar_event, is_active) VALUES
  ('plan_confirmation', 'Plan Confirmation Rule', 'File Motion to Confirm Chapter 13 Plan — attach proposed order', 7, 'medium', true, true),
  ('notice_of_conversion', 'Notice of Conversion Rule', 'Process Notice of Conversion and update case type in system', 3, 'high', true, true),
  ('motion_to_convert', 'Motion to Convert Rule', 'Prepare and file Motion to Convert — attach supporting documents', 14, 'medium', true, true),
  ('voluntary_dismissal', 'Voluntary Dismissal Rule', 'File Motion to Voluntarily Dismiss Case — confirm client authorization', 5, 'medium', false, true),
  ('lien_avoidance', 'Lien Avoidance Rule', 'Prepare Motion to Avoid Judicial Lien — pull judgment search and property valuation', 21, 'high', true, true),
  ('motion_to_value', 'Motion to Value Rule', 'Prepare Motion to Value Collateral — order appraisal and title search', 21, 'high', true, true)
ON CONFLICT DO NOTHING;

-- ── New Pleading Templates ────────────────────────────────────────────────────
INSERT INTO pleading_templates (name, category, applicable_filing_type, content_template) VALUES
(
  'Motion to Confirm Chapter 13 Plan',
  'motion_response',
  'plan_confirmation',
  E'IN THE UNITED STATES BANKRUPTCY COURT\nFOR THE {{DISTRICT}} DISTRICT OF {{STATE}}\n\nIn re:\n\n{{DEBTOR_NAME}},\n\n          Debtor.\n\nCase No.: {{CASE_NUMBER}}\nChapter 13\n\nDEBTOR''S MOTION TO CONFIRM CHAPTER 13 PLAN\n\nComes now the Debtor, {{DEBTOR_NAME}}, by and through undersigned counsel, and respectfully moves this Court to confirm the Chapter 13 Plan filed herein, and in support thereof states:\n\n1. The Debtor filed a voluntary petition under Chapter 13 of the Bankruptcy Code on {{FILING_DATE}}.\n\n2. The Debtor''s Chapter 13 Plan ("Plan") was filed on {{PLAN_FILED_DATE}} and provides for monthly payments of ${{MONTHLY_PAYMENT}} to the Chapter 13 Trustee for a period of {{PLAN_MONTHS}} months.\n\n3. The Plan complies with all applicable provisions of 11 U.S.C. § 1325, including:\n\n   a. The Plan has been proposed in good faith and not by any means forbidden by law;\n\n   b. The value of property to be distributed under the Plan to each allowed unsecured creditor is not less than the amount that would be paid on such claim if the estate were liquidated under Chapter 7 on the effective date of the Plan;\n\n   c. The Plan is feasible — the Debtor will be able to make all payments and comply with the Plan;\n\n   d. All priority claims required by 11 U.S.C. § 507 will be paid in full;\n\n   e. {{ADDITIONAL_CONFIRMATION_REQUIREMENTS}}.\n\n4. The Debtor''s monthly disposable income, as calculated on Official Form 122C-2, is ${{DISPOSABLE_INCOME}}.\n\n5. No timely objections to confirmation have been filed, or all objections have been resolved.\n\nWHEREFORE, the Debtor respectfully requests that this Court enter an Order confirming the Chapter 13 Plan.\n\nRespectfully submitted,\n\n{{ATTORNEY_NAME}}\n{{FIRM_NAME}}\nBar No.: {{BAR_NUMBER}}\nCounsel for Debtor'
),
(
  'Notice of Conversion to Chapter 7',
  'general',
  'notice_of_conversion',
  E'IN THE UNITED STATES BANKRUPTCY COURT\nFOR THE {{DISTRICT}} DISTRICT OF {{STATE}}\n\nIn re:\n\n{{DEBTOR_NAME}},\n\n          Debtor.\n\nCase No.: {{CASE_NUMBER}}\nChapter {{FROM_CHAPTER}}\n\nNOTICE OF CONVERSION TO CHAPTER 7\n\nPLEASE TAKE NOTICE that pursuant to 11 U.S.C. § {{CONVERSION_STATUTE}}, the above-captioned Debtor hereby converts this case from Chapter {{FROM_CHAPTER}} to Chapter 7 of the Bankruptcy Code.\n\nThe Debtor elects to convert this case for the following reason(s):\n\n{{CONVERSION_REASONS}}\n\nThe Debtor represents that:\n\n1. This case was not previously converted under 11 U.S.C. §§ 1112, 1208, or 1307;\n\n2. The Debtor is eligible to be a debtor under Chapter 7 pursuant to 11 U.S.C. § 109(b);\n\n3. The conversion filing fee of ${{CONVERSION_FEE}} has been paid or is being tendered herewith.\n\nThe Debtor will file updated Schedules, Means Test (if applicable), and all other required Chapter 7 documents within the time permitted by the Federal Rules of Bankruptcy Procedure.\n\nRespectfully submitted,\n\n{{ATTORNEY_NAME}}\n{{FIRM_NAME}}\nBar No.: {{BAR_NUMBER}}\nCounsel for Debtor'
),
(
  'Motion to Convert from Chapter 7 to Chapter 13',
  'motion_response',
  'motion_to_convert',
  E'IN THE UNITED STATES BANKRUPTCY COURT\nFOR THE {{DISTRICT}} DISTRICT OF {{STATE}}\n\nIn re:\n\n{{DEBTOR_NAME}},\n\n          Debtor.\n\nCase No.: {{CASE_NUMBER}}\nChapter 7\n\nDEBTOR''S MOTION TO CONVERT CASE FROM CHAPTER 7 TO CHAPTER 13\n\nComes now the Debtor, {{DEBTOR_NAME}}, by and through undersigned counsel, and pursuant to 11 U.S.C. § 706(a), moves this Court for an Order converting this case from Chapter 7 to Chapter 13, and in support thereof states:\n\nI. INTRODUCTION\n\nThe Debtor respectfully requests conversion of this Chapter 7 case to Chapter 13 to allow the Debtor to cure mortgage arrears, retain non-exempt property, and propose a repayment plan to creditors.\n\nII. ELIGIBILITY\n\n1. This case was not previously converted from Chapter 13, 11, or 12.\n\n2. The Debtor is eligible for Chapter 13 relief — the Debtor''s secured debt does not exceed ${{SECURED_DEBT_LIMIT}} and unsecured debt does not exceed ${{UNSECURED_DEBT_LIMIT}} (11 U.S.C. § 109(e)).\n\n3. The Debtor has regular income sufficient to fund a Chapter 13 plan.\n\nIII. GROUNDS FOR CONVERSION\n\n{{GROUNDS_FOR_CONVERSION}}\n\nIV. PROPOSED PLAN SUMMARY\n\nThe Debtor proposes to pay approximately ${{MONTHLY_PAYMENT}} per month for {{PLAN_MONTHS}} months, which will:\n\n- Cure mortgage arrears of approximately ${{MORTGAGE_ARREARS}};\n- Pay priority claims in full;\n- Pay general unsecured creditors approximately {{UNSECURED_PERCENT}}% of their allowed claims.\n\nV. CONCLUSION\n\nFor the foregoing reasons, the Debtor respectfully requests that this Court enter an Order converting this case from Chapter 7 to Chapter 13.\n\nRespectfully submitted,\n\n{{ATTORNEY_NAME}}\n{{FIRM_NAME}}\nBar No.: {{BAR_NUMBER}}\nCounsel for Debtor'
),
(
  'Motion to Voluntarily Dismiss Case',
  'general',
  'voluntary_dismissal',
  E'IN THE UNITED STATES BANKRUPTCY COURT\nFOR THE {{DISTRICT}} DISTRICT OF {{STATE}}\n\nIn re:\n\n{{DEBTOR_NAME}},\n\n          Debtor.\n\nCase No.: {{CASE_NUMBER}}\nChapter {{CHAPTER}}\n\nDEBTOR''S MOTION TO VOLUNTARILY DISMISS CHAPTER {{CHAPTER}} CASE\n\nComes now the Debtor, {{DEBTOR_NAME}}, by and through undersigned counsel, and pursuant to 11 U.S.C. § {{DISMISSAL_STATUTE}}, moves this Court to dismiss the above-captioned bankruptcy case, and in support thereof states:\n\n1. The Debtor filed this voluntary bankruptcy petition on {{FILING_DATE}}.\n\n2. The Debtor requests dismissal of this case for the following reason(s):\n\n   {{DISMISSAL_REASONS}}\n\n3. {{CREDITOR_IMPACT_STATEMENT}}\n\n4. No trustee has been appointed, or the appointed trustee has been notified of this motion and {{TRUSTEE_POSITION}}.\n\n5. Dismissal of this case {{WILL_OR_WILL_NOT}} prejudice any creditor.\n\n6. The Debtor understands that upon dismissal:\n\n   a. The automatic stay will be terminated;\n   b. Any property of the estate will revest in the Debtor;\n   c. {{RE_FILING_RESTRICTIONS}}.\n\nWHEREFORE, the Debtor respectfully requests that this Court enter an Order dismissing this bankruptcy case.\n\nRespectfully submitted,\n\n{{ATTORNEY_NAME}}\n{{FIRM_NAME}}\nBar No.: {{BAR_NUMBER}}\nCounsel for Debtor'
),
(
  'Motion to Avoid Judicial Lien',
  'motion_response',
  'lien_avoidance',
  E'IN THE UNITED STATES BANKRUPTCY COURT\nFOR THE {{DISTRICT}} DISTRICT OF {{STATE}}\n\nIn re:\n\n{{DEBTOR_NAME}},\n\n          Debtor.\n\nCase No.: {{CASE_NUMBER}}\nChapter {{CHAPTER}}\n\nDEBTOR''S MOTION TO AVOID JUDICIAL LIEN PURSUANT TO 11 U.S.C. § 522(f)\n\nComes now the Debtor, {{DEBTOR_NAME}}, by and through undersigned counsel, and pursuant to 11 U.S.C. § 522(f)(1)(A), moves this Court to avoid the judicial lien of {{JUDGMENT_CREDITOR}} on the Debtor''s exempt property, and in support thereof states:\n\nI. PROPERTY SUBJECT TO LIEN\n\n1. The property subject to the judicial lien is located at:\n   {{PROPERTY_ADDRESS}}\n   {{PROPERTY_CITY}}, {{PROPERTY_STATE}} {{PROPERTY_ZIP}}\n\n2. The property is the Debtor''s {{HOMESTEAD_OR_OTHER}} and is claimed as exempt under {{EXEMPTION_STATUTE}}.\n\nII. THE JUDICIAL LIEN\n\n3. {{JUDGMENT_CREDITOR}} holds a judicial lien on the above property by virtue of a judgment entered on {{JUDGMENT_DATE}} in {{JUDGMENT_COURT}}, Case No. {{JUDGMENT_CASE_NUMBER}}, in the amount of ${{JUDGMENT_AMOUNT}}.\n\n4. The judgment lien was recorded/docketed on {{LIEN_RECORDED_DATE}}.\n\nIII. CALCULATION OF IMPAIRMENT\n\n5. The following encumbrances exist on the property:\n   a. Fair market value of property:                    ${{FMV}}\n   b. Senior liens (mortgages, taxes, etc.):           (${{SENIOR_LIENS}})\n   c. Applicable exemption:                            (${{EXEMPTION_AMOUNT}})\n   d. Amount available to judicial lien:                ${{AVAILABLE_TO_LIEN}}\n\n6. Because the judicial lien of ${{JUDGMENT_AMOUNT}} exceeds the amount available (${{AVAILABLE_TO_LIEN}}), the lien impairs the Debtor''s exemption pursuant to 11 U.S.C. § 522(f)(2)(A).\n\n7. Specifically, the formula under § 522(f)(2)(A) yields:\n   (${{SENIOR_LIENS}} + ${{JUDGMENT_AMOUNT}} + ${{EXEMPTION_AMOUNT}}) - ${{FMV}} = ${{IMPAIRMENT_AMOUNT}}\n   The lien is avoided to the extent of ${{AVOIDANCE_AMOUNT}}.\n\nIV. CONCLUSION\n\nFor the foregoing reasons, the Debtor respectfully requests that this Court enter an Order avoiding the judicial lien of {{JUDGMENT_CREDITOR}} in the amount of ${{AVOIDANCE_AMOUNT}} on the Debtor''s exempt property.\n\nRespectfully submitted,\n\n{{ATTORNEY_NAME}}\n{{FIRM_NAME}}\nBar No.: {{BAR_NUMBER}}\nCounsel for Debtor'
),
(
  'Motion to Value Collateral (Cram Down)',
  'motion_response',
  'motion_to_value',
  E'IN THE UNITED STATES BANKRUPTCY COURT\nFOR THE {{DISTRICT}} DISTRICT OF {{STATE}}\n\nIn re:\n\n{{DEBTOR_NAME}},\n\n          Debtor.\n\nCase No.: {{CASE_NUMBER}}\nChapter {{CHAPTER}}\n\nDEBTOR''S MOTION TO VALUE COLLATERAL AND MODIFY SECURED CLAIM\nPURSUANT TO 11 U.S.C. § 506(a) AND FED. R. BANKR. P. 3012\n\nComes now the Debtor, {{DEBTOR_NAME}}, by and through undersigned counsel, and moves this Court to determine the value of the collateral securing the claim of {{CREDITOR_NAME}} and to modify the secured claim accordingly, and in support thereof states:\n\nI. INTRODUCTION\n\nPursuant to 11 U.S.C. § 506(a), the Debtor seeks a determination that the secured claim of {{CREDITOR_NAME}} ("Creditor") is limited to the current value of its collateral. The balance of the claim shall be treated as an unsecured claim subject to the Debtor''s Chapter {{CHAPTER}} Plan.\n\nII. DESCRIPTION OF COLLATERAL\n\n1. The collateral at issue is: {{COLLATERAL_DESCRIPTION}}\n\n2. {{COLLATERAL_LOCATION_OR_VIN}}\n\n3. Current fair market value of collateral: ${{COLLATERAL_FMV}}\n   Basis for valuation: {{VALUATION_BASIS}} (e.g., NADA, KBB, appraisal, comparables)\n\nIII. THE CREDITOR''S CLAIM\n\n4. {{CREDITOR_NAME}} filed/holds a {{SECURED_OR_SCHEDULED}} claim in the amount of ${{TOTAL_CLAIM_AMOUNT}}.\n\n5. The lien was perfected on {{LIEN_DATE}} and encumbers the collateral described above.\n\n6. The debt was incurred on {{DEBT_INCURRED_DATE}}.\n\nIV. BIFURCATION OF CLAIM UNDER § 506(a)\n\n7. Pursuant to 11 U.S.C. § 506(a), the claim of {{CREDITOR_NAME}} is bifurcated as follows:\n   a. Secured portion (= collateral value):    ${{COLLATERAL_FMV}}\n   b. Unsecured portion (= deficiency):        ${{UNSECURED_DEFICIENCY}}\n\n8. The Debtor''s Chapter {{CHAPTER}} Plan proposes to pay the secured claim of ${{COLLATERAL_FMV}} with interest at the Till rate of {{INTEREST_RATE}}% per annum, with monthly payments of ${{MONTHLY_PAYMENT}}.\n\n9. The unsecured deficiency of ${{UNSECURED_DEFICIENCY}} shall be treated as a general unsecured claim and receive pro-rata distribution with other unsecured creditors.\n\nV. APPLICABLE LAW\n\n10. {{ANTI_MODIFICATION_EXCEPTION_ANALYSIS}} (address whether the 910-day rule or § 1325(a)(*) anti-modification clause applies).\n\nVI. CONCLUSION\n\nFor the foregoing reasons, the Debtor respectfully requests that this Court enter an Order:\n\n(a) Determining the value of the collateral to be ${{COLLATERAL_FMV}};\n(b) Determining that the secured claim of {{CREDITOR_NAME}} is ${{COLLATERAL_FMV}};\n(c) Determining that the remaining balance of ${{UNSECURED_DEFICIENCY}} is an unsecured claim;\n(d) Confirming that the Debtor''s Chapter {{CHAPTER}} Plan treatment of this claim is proper.\n\nRespectfully submitted,\n\n{{ATTORNEY_NAME}}\n{{FIRM_NAME}}\nBar No.: {{BAR_NUMBER}}\nCounsel for Debtor'
)
ON CONFLICT DO NOTHING;
