/*
  # Workflow, Staff Dashboard, and Attorney Availability Schema

  ## Summary
  This migration adds the tables needed for:
  1. Attorney availability rules (which chapters they file, which days they do signings, max signings/day)
  2. Hearing buffer enforcement (no signings 2h before / 1.5h after a hearing)
  3. Hearing reassignment flow (attorney delegates a hearing to another attorney)
  4. Staff task queue (tasks assigned to staff members with due dates, priority, case workflow step)
  5. Case workflow status tracking (what stage each client file is in)

  ## New Tables

  ### attorney_availability
  Per-attorney rules: which chapters they handle, which days they accept signings, max signings per day.
  - id, staff_id (FK staff_members), chapters_handled (text[] e.g. ['7','13']),
    signing_days (int[] day-of-week 0=Sun..6=Sat),
    max_signings_per_day (int DEFAULT 4),
    hearing_buffer_before_minutes (int DEFAULT 120),
    hearing_buffer_after_minutes (int DEFAULT 90),
    created_at, updated_at

  ### hearing_reassignments
  When an attorney reassigns a hearing to another attorney.
  - id, event_id (FK calendar_events), from_staff_id, to_staff_id,
    status ('pending_acceptance'|'accepted'|'declined'),
    requested_at, responded_at, notes

  ### staff_tasks
  Task queue for each staff member. Tasks are auto-generated by the workflow engine
  when a case advances to a new step, or manually created.
  - id, assigned_to (staff_id FK), client_id, client_name,
    task_type (text: 'doc_review'|'attorney_review'|'paralegal_review'|'schedule_signing'|'collect_filing_fee'|'upload_missing_docs'|'manual'),
    title, description, priority ('low'|'normal'|'high'|'urgent'),
    status ('pending'|'in_progress'|'completed'|'blocked'|'cancelled'),
    due_date (date), completed_at, created_at, updated_at

  ### case_workflow_status
  Single row per client tracking their current workflow stage and gate checks.
  - id, client_id (unique FK),
    stage: 'intake'|'paralegal_review'|'attorney_review'|'filing_fee_pending'|'docs_missing'|'ready_to_schedule'|'scheduled'|'filed'|'closed',
    paralegal_review_complete (bool), paralegal_reviewed_by, paralegal_reviewed_at,
    attorney_review_complete (bool), attorney_reviewed_by, attorney_reviewed_at,
    filing_fee_paid (bool), filing_fee_paid_at,
    missing_docs_cleared (bool),
    scheduling_approved (bool), scheduling_approved_at,
    signing_event_id (FK calendar_events nullable),
    signed_at,
    filed_at,
    notes,
    created_at, updated_at

  ## Security
  - RLS enabled on all tables
  - Anon access allowed (matches project pattern)
*/

-- ── attorney_availability ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS attorney_availability (
  id                            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id                      uuid NOT NULL,
  chapters_handled              text[] NOT NULL DEFAULT ARRAY['7'],
  signing_days                  int[] NOT NULL DEFAULT ARRAY[1,2,3,4,5],
  max_signings_per_day          int NOT NULL DEFAULT 4,
  hearing_buffer_before_minutes int NOT NULL DEFAULT 120,
  hearing_buffer_after_minutes  int NOT NULL DEFAULT 90,
  notes                         text,
  created_at                    timestamptz NOT NULL DEFAULT now(),
  updated_at                    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE attorney_availability ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anon select attorney_availability" ON attorney_availability FOR SELECT TO anon USING (true);
CREATE POLICY "Anon insert attorney_availability" ON attorney_availability FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Anon update attorney_availability" ON attorney_availability FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Auth select attorney_availability" ON attorney_availability FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert attorney_availability" ON attorney_availability FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update attorney_availability" ON attorney_availability FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- ── hearing_reassignments ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS hearing_reassignments (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id         uuid NOT NULL,
  from_staff_id    uuid NOT NULL,
  to_staff_id      uuid NOT NULL,
  status           text NOT NULL DEFAULT 'pending_acceptance',
  requested_at     timestamptz NOT NULL DEFAULT now(),
  responded_at     timestamptz,
  notes            text,
  created_at       timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE hearing_reassignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anon select hearing_reassignments" ON hearing_reassignments FOR SELECT TO anon USING (true);
CREATE POLICY "Anon insert hearing_reassignments" ON hearing_reassignments FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Anon update hearing_reassignments" ON hearing_reassignments FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Auth select hearing_reassignments" ON hearing_reassignments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert hearing_reassignments" ON hearing_reassignments FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update hearing_reassignments" ON hearing_reassignments FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- ── staff_tasks ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS staff_tasks (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  assigned_to  uuid,
  client_id    uuid,
  client_name  text NOT NULL DEFAULT '',
  task_type    text NOT NULL DEFAULT 'manual',
  title        text NOT NULL DEFAULT '',
  description  text,
  priority     text NOT NULL DEFAULT 'normal',
  status       text NOT NULL DEFAULT 'pending',
  due_date     date,
  completed_at timestamptz,
  created_by   text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE staff_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anon select staff_tasks" ON staff_tasks FOR SELECT TO anon USING (true);
CREATE POLICY "Anon insert staff_tasks" ON staff_tasks FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Anon update staff_tasks" ON staff_tasks FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Auth select staff_tasks" ON staff_tasks FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert staff_tasks" ON staff_tasks FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update staff_tasks" ON staff_tasks FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- ── case_workflow_status ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS case_workflow_status (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id                 uuid NOT NULL UNIQUE,
  client_name               text NOT NULL DEFAULT '',
  chapter                   text NOT NULL DEFAULT '7',
  stage                     text NOT NULL DEFAULT 'intake',
  paralegal_review_complete bool NOT NULL DEFAULT false,
  paralegal_reviewed_by     text,
  paralegal_reviewed_at     timestamptz,
  attorney_review_complete  bool NOT NULL DEFAULT false,
  attorney_reviewed_by      text,
  attorney_reviewed_at      timestamptz,
  filing_fee_paid           bool NOT NULL DEFAULT false,
  filing_fee_paid_at        timestamptz,
  missing_docs_cleared      bool NOT NULL DEFAULT true,
  missing_docs_list         text[],
  scheduling_approved       bool NOT NULL DEFAULT false,
  scheduling_approved_at    timestamptz,
  signing_event_id          uuid,
  signed_at                 timestamptz,
  filed_at                  timestamptz,
  notes                     text,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE case_workflow_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anon select case_workflow_status" ON case_workflow_status FOR SELECT TO anon USING (true);
CREATE POLICY "Anon insert case_workflow_status" ON case_workflow_status FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Anon update case_workflow_status" ON case_workflow_status FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Auth select case_workflow_status" ON case_workflow_status FOR SELECT TO authenticated USING (true);
CREATE POLICY "Auth insert case_workflow_status" ON case_workflow_status FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth update case_workflow_status" ON case_workflow_status FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_attorney_availability_staff_id ON attorney_availability(staff_id);
CREATE INDEX IF NOT EXISTS idx_hearing_reassignments_event_id ON hearing_reassignments(event_id);
CREATE INDEX IF NOT EXISTS idx_hearing_reassignments_to_staff ON hearing_reassignments(to_staff_id);
CREATE INDEX IF NOT EXISTS idx_staff_tasks_assigned_to ON staff_tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_staff_tasks_client_id ON staff_tasks(client_id);
CREATE INDEX IF NOT EXISTS idx_staff_tasks_status ON staff_tasks(status);
CREATE INDEX IF NOT EXISTS idx_case_workflow_status_client_id ON case_workflow_status(client_id);
CREATE INDEX IF NOT EXISTS idx_case_workflow_status_stage ON case_workflow_status(stage);
